version: '2'
services:
  boilerplate-api:
    build: .
    environment:
      - MONGO_URI=mongodb+srv://booking-app:Khang%402311@cluster0.sdmle.mongodb.net/booking-app?retryWrites=true&w=majority
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
